import {
  Patient,
  Doctor,
  Hospital,
  Appointment,
  MedicalRecord,
  LabReport,
  Prescription,
  PrescriptionOrder,
  InventoryItem,
  Referral,
  HealthAssessment,
  FollowUp,
  BedCategory,
  Notification,
} from '../../types';

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    userId: 'usr-pat-1',
    name: 'Ravi Patil',
    phone: '+91 98765 43210',
    dateOfBirth: '1985-04-12',
    age: 41,
    gender: 'Male',
    bloodGroup: 'O+',
    address: 'House #42, Main Bajar',
    village: 'Khed',
    district: 'Pune',
    state: 'Maharashtra',
    emergencyContact: '+91 98765 43211 (Brother)',
    preferredLanguage: 'hi',
    medicalHistory: ['Hypertension (2 yrs)', 'Mild Asthma'],
    allergies: ['Penicillin'],
    currentRisk: 'MEDIUM',
  },
  {
    id: 'pat-2',
    userId: 'usr-pat-2',
    name: 'Sunita More',
    phone: '+91 98234 56789',
    dateOfBirth: '1992-09-24',
    age: 33,
    gender: 'Female',
    bloodGroup: 'B+',
    address: 'Near Gram Panchayat Office',
    village: 'Anandpur',
    district: 'Pune',
    state: 'Maharashtra',
    emergencyContact: '+91 98234 56788 (Husband)',
    preferredLanguage: 'en',
    medicalHistory: ['Gestational Diabetes (2023)'],
    allergies: ['None'],
    currentRisk: 'HIGH',
  },
  {
    id: 'pat-3',
    userId: 'usr-pat-3',
    name: 'Asha Shinde',
    phone: '+91 97112 33445',
    dateOfBirth: '1958-11-03',
    age: 67,
    gender: 'Female',
    bloodGroup: 'A+',
    address: 'Wadi No 3',
    village: 'Manchar',
    district: 'Pune',
    state: 'Maharashtra',
    emergencyContact: '+91 97112 33446 (Son)',
    preferredLanguage: 'hi',
    medicalHistory: ['Type 2 Diabetes', 'Osteoarthritis'],
    allergies: ['Sulfa drugs'],
    currentRisk: 'LOW',
  },
  {
    id: 'pat-4',
    userId: 'usr-pat-4',
    name: 'Mahesh Jadhav',
    phone: '+91 99887 76655',
    dateOfBirth: '2001-02-18',
    age: 25,
    gender: 'Male',
    bloodGroup: 'AB+',
    address: 'Station Road',
    village: 'Junnar',
    district: 'Pune',
    state: 'Maharashtra',
    emergencyContact: '+91 99887 76654 (Father)',
    preferredLanguage: 'en',
    medicalHistory: ['Fracture Right Arm (2024)'],
    allergies: ['None'],
    currentRisk: 'CRITICAL',
  },
];

export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-1',
    name: 'Primary Health Centre (PHC) Khed',
    registrationNumber: 'MH-PHC-2041',
    type: 'PHC',
    address: 'Station Road, Khed Town',
    village: 'Khed',
    district: 'Pune',
    state: 'Maharashtra',
    latitude: 18.8471,
    longitude: 73.9056,
    phone: '+91 2135 222100',
    email: 'phc.khed@dhs.mh.gov.in',
    emergencyAvailable: true,
    services: ['General OPD', 'Maternal & Child Health', 'Vaccination', 'Basic Diagnostics', 'Pharmacy'],
    distanceKm: 2.4,
    availableBeds: 12,
    totalBeds: 20,
  },
  {
    id: 'hosp-2',
    name: 'Community Health Centre (CHC) Manchar',
    registrationNumber: 'MH-CHC-1088',
    type: 'CHC',
    address: 'NH-60 Bypass Road, Manchar',
    village: 'Manchar',
    district: 'Pune',
    state: 'Maharashtra',
    latitude: 19.0022,
    longitude: 73.9431,
    phone: '+91 2133 224410',
    email: 'chc.manchar@dhs.mh.gov.in',
    emergencyAvailable: true,
    services: ['24/7 Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics', 'X-Ray & Pathology'],
    distanceKm: 14.8,
    availableBeds: 28,
    totalBeds: 50,
  },
  {
    id: 'hosp-3',
    name: 'District Hospital Aundh (Pune)',
    registrationNumber: 'MH-DH-0012',
    type: 'DISTRICT_HOSPITAL',
    address: 'Aundh Camp Road, Pune',
    district: 'Pune',
    state: 'Maharashtra',
    latitude: 18.5626,
    longitude: 73.8087,
    phone: '+91 20 2728 1122',
    email: 'dh.aundh@maharashtra.gov.in',
    emergencyAvailable: true,
    services: ['ICU & Trauma', 'Cardiology', 'Nephrology', 'Dialysis', 'Blood Bank', 'CT Scan', 'Specialist OPD'],
    distanceKm: 34.0,
    availableBeds: 74,
    totalBeds: 300,
  },
  {
    id: 'hosp-4',
    name: 'Health & Wellness Sub-Center Anandpur',
    registrationNumber: 'MH-SC-4401',
    type: 'SUB_CENTER',
    address: 'Zilla Parishad School Road, Anandpur',
    village: 'Anandpur',
    district: 'Pune',
    state: 'Maharashtra',
    latitude: 18.8912,
    longitude: 73.8821,
    phone: '+91 94220 11223',
    emergencyAvailable: false,
    services: ['First Aid', 'ASHA/ANM Base', 'Immunization', 'NCD Screening'],
    distanceKm: 1.1,
    availableBeds: 2,
    totalBeds: 4,
  },
];

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    userId: 'usr-doc-1',
    name: 'Dr. Anand Deshmukh',
    specialization: 'General Medicine / MD',
    qualification: 'MBBS, MD (Internal Medicine)',
    registrationNumber: 'MCI-2012-44910',
    experienceYears: 14,
    consultationFee: 0,
    isAvailable: true,
    hospitalId: 'hosp-1',
    hospitalName: 'Primary Health Centre (PHC) Khed',
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    rating: 4.8,
  },
  {
    id: 'doc-2',
    userId: 'usr-doc-2',
    name: 'Dr. Priya Kulkarni',
    specialization: 'Obstetrics & Gynecology',
    qualification: 'MBBS, DGO, MS',
    registrationNumber: 'MCI-2015-88219',
    experienceYears: 10,
    consultationFee: 0,
    isAvailable: true,
    hospitalId: 'hosp-2',
    hospitalName: 'Community Health Centre (CHC) Manchar',
    availableDays: ['Mon', 'Wed', 'Fri'],
    rating: 4.9,
  },
  {
    id: 'doc-3',
    userId: 'usr-doc-3',
    name: 'Dr. Vikram Joshi',
    specialization: 'Cardiology Specialist',
    qualification: 'MBBS, MD, DM (Cardiology)',
    registrationNumber: 'MCI-2008-11204',
    experienceYears: 18,
    consultationFee: 0,
    isAvailable: true,
    hospitalId: 'hosp-3',
    hospitalName: 'District Hospital Aundh (Pune)',
    availableDays: ['Tue', 'Thu', 'Sat'],
    rating: 4.95,
  },
  {
    id: 'doc-4',
    userId: 'usr-doc-4',
    name: 'Dr. Sunita Ranade',
    specialization: 'Pediatrics & Child Care',
    qualification: 'MBBS, DCH',
    registrationNumber: 'MCI-2018-99012',
    experienceYears: 7,
    consultationFee: 0,
    isAvailable: true,
    hospitalId: 'hosp-2',
    hospitalName: 'Community Health Centre (CHC) Manchar',
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    rating: 4.7,
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-101',
    patientId: 'pat-1',
    patientName: 'Ravi Patil',
    doctorId: 'doc-1',
    doctorName: 'Dr. Anand Deshmukh',
    doctorSpecialization: 'General Medicine / MD',
    hospitalId: 'hosp-1',
    hospitalName: 'Primary Health Centre (PHC) Khed',
    appointmentDate: '2026-09-06',
    startTime: '10:00',
    endTime: '10:15',
    tokenNumber: 4,
    status: 'IN_CONSULTATION',
    priority: 'HIGH',
    reason: 'Persistent fever & chest tightness for 3 days',
    createdAt: '2026-09-05T14:20:00Z',
  },
  {
    id: 'apt-102',
    patientId: 'pat-2',
    patientName: 'Sunita More',
    doctorId: 'doc-2',
    doctorName: 'Dr. Priya Kulkarni',
    doctorSpecialization: 'Obstetrics & Gynecology',
    hospitalId: 'hosp-2',
    hospitalName: 'Community Health Centre (CHC) Manchar',
    appointmentDate: '2026-09-06',
    startTime: '11:30',
    endTime: '11:45',
    tokenNumber: 8,
    status: 'CHECKED_IN',
    priority: 'NORMAL',
    reason: 'Routine antenatal checkup (3rd Trimester)',
    createdAt: '2026-09-04T09:15:00Z',
  },
  {
    id: 'apt-103',
    patientId: 'pat-4',
    patientName: 'Mahesh Jadhav',
    doctorId: 'doc-3',
    doctorName: 'Dr. Vikram Joshi',
    doctorSpecialization: 'Cardiology Specialist',
    hospitalId: 'hosp-3',
    hospitalName: 'District Hospital Aundh (Pune)',
    appointmentDate: '2026-09-06',
    startTime: '09:15',
    endTime: '09:30',
    tokenNumber: 1,
    status: 'BOOKED',
    priority: 'EMERGENCY',
    reason: 'Severe sudden arrhythmia and syncope',
    createdAt: '2026-09-06T06:00:00Z',
  },
];

export const INITIAL_MEDICAL_RECORDS: MedicalRecord[] = [
  {
    id: 'rec-1',
    patientId: 'pat-1',
    doctorId: 'doc-1',
    doctorName: 'Dr. Anand Deshmukh',
    hospitalId: 'hosp-1',
    hospitalName: 'PHC Khed',
    recordType: 'CONSULTATION',
    diagnosis: 'Acute Upper Respiratory Tract Infection & Mild BP Elevation',
    notes: 'BP recorded 142/90 mmHg. Lungs clear. Advised hydration and salt reduction.',
    treatment: 'Tab Paracetamol 650mg TDS x 3 days, Tab Amlodipine 5mg OD x 15 days.',
    createdAt: '2026-08-20T10:30:00Z',
  },
  {
    id: 'rec-2',
    patientId: 'pat-3',
    doctorId: 'doc-1',
    doctorName: 'Dr. Anand Deshmukh',
    hospitalId: 'hosp-1',
    hospitalName: 'PHC Khed',
    recordType: 'CHECKUP',
    diagnosis: 'Type 2 Diabetes Mellitus - Routine Review',
    notes: 'HbA1c last month 7.2%. No signs of diabetic neuropathy.',
    treatment: 'Tab Metformin 500mg BD after meals.',
    createdAt: '2026-08-10T11:00:00Z',
  },
];

export const INITIAL_LAB_REPORTS: LabReport[] = [
  {
    id: 'lab-1',
    patientId: 'pat-1',
    patientName: 'Ravi Patil',
    hospitalId: 'hosp-1',
    hospitalName: 'PHC Khed Pathology Lab',
    uploadedBy: 'Tech. Suresh Mane',
    fileUrl: '/mock/lab_cbc_ravi.pdf',
    reportType: 'Complete Blood Count (CBC) & Sugar',
    extractedText: 'Hemoglobin: 13.5 g/dL, WBC: 11,200 /uL, Fasting Sugar: 118 mg/dL',
    reportDate: '2026-09-01',
    status: 'REVIEWED',
    results: [
      { id: 'lr-1', parameter: 'Hemoglobin', value: '13.5', unit: 'g/dL', referenceRange: '13.0 - 17.0', abnormalFlag: false },
      { id: 'lr-2', parameter: 'WBC Total Count', value: '11200', unit: '/uL', referenceRange: '4000 - 10000', abnormalFlag: true },
      { id: 'lr-3', parameter: 'Fasting Blood Sugar', value: '118', unit: 'mg/dL', referenceRange: '70 - 100', abnormalFlag: true },
    ],
  },
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-1',
    patientId: 'pat-1',
    patientName: 'Ravi Patil',
    doctorId: 'doc-1',
    doctorName: 'Dr. Anand Deshmukh',
    appointmentId: 'apt-101',
    instructions: 'Take medicines after meals with warm water.',
    createdAt: '2026-08-20T10:35:00Z',
    medicines: [
      { id: 'pm-1', medicineId: 'med-1', medicineName: 'Paracetamol 650mg', dosage: '1 Tablet', frequency: '1-0-1 (Twice daily)', duration: '5 days', instructions: 'Take after food' },
      { id: 'pm-2', medicineId: 'med-2', medicineName: 'Amoxicillin 500mg', dosage: '1 Capsule', frequency: '1-0-1 (Twice daily)', duration: '5 days', instructions: 'Complete full course' },
      { id: 'pm-3', medicineId: 'med-3', medicineName: 'Amlodipine 5mg', dosage: '1 Tablet', frequency: '1-0-0 (Morning)', duration: '30 days', instructions: 'Daily morning' },
    ],
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  { id: 'inv-1', pharmacyId: 'pharm-1', medicineId: 'med-1', medicineName: 'Paracetamol 650mg Strip', category: 'Analgesics', quantity: 450, batchNumber: 'PCM-2026-08', expiryDate: '2027-08-31', price: 18.5, isLowStock: false },
  { id: 'inv-2', pharmacyId: 'pharm-1', medicineId: 'med-2', medicineName: 'Amoxicillin 500mg Strip', category: 'Antibiotics', quantity: 24, batchNumber: 'AMX-2025-11', expiryDate: '2026-11-30', price: 65.0, isLowStock: true },
  { id: 'inv-3', pharmacyId: 'pharm-1', medicineId: 'med-3', medicineName: 'Amlodipine 5mg Strip', category: 'Cardiovascular', quantity: 300, batchNumber: 'AML-2026-03', expiryDate: '2028-02-28', price: 22.0, isLowStock: false },
  { id: 'inv-4', pharmacyId: 'pharm-1', medicineId: 'med-4', medicineName: 'ORSPouch 21.8g', category: 'Rehydration', quantity: 8, batchNumber: 'ORS-2025-09', expiryDate: '2026-10-15', price: 5.0, isLowStock: true },
];

export const INITIAL_PRESCRIPTION_ORDERS: PrescriptionOrder[] = [
  {
    id: 'ord-101',
    prescriptionId: 'rx-1',
    patientName: 'Ravi Patil',
    patientPhone: '+91 98765 43210',
    doctorName: 'Dr. Anand Deshmukh',
    hospitalName: 'PHC Khed',
    orderDate: '2026-08-20T11:00:00Z',
    status: 'PENDING',
    medicines: [
      { id: 'pm-1', medicineId: 'med-1', medicineName: 'Paracetamol 650mg', dosage: '1 Tablet', frequency: '1-0-1', duration: '5 days' },
      { id: 'pm-2', medicineId: 'med-2', medicineName: 'Amoxicillin 500mg', dosage: '1 Capsule', frequency: '1-0-1', duration: '5 days' },
    ],
    totalPrice: 83.5,
  },
];

export const INITIAL_REFERRALS: Referral[] = [
  {
    id: 'ref-1',
    patientId: 'pat-2',
    patientName: 'Sunita More',
    fromHospitalId: 'hosp-4',
    fromHospitalName: 'Health & Wellness Sub-Center Anandpur',
    toHospitalId: 'hosp-2',
    toHospitalName: 'Community Health Centre (CHC) Manchar',
    doctorId: 'doc-2',
    doctorName: 'Dr. Priya Kulkarni',
    reason: 'Gestational hypertension and borderline pre-eclampsia monitoring',
    priority: 'HIGH',
    status: 'ACCEPTED',
    createdAt: '2026-09-03T08:00:00Z',
    currentStage: 'Scheduled',
  },
  {
    id: 'ref-2',
    patientId: 'pat-4',
    patientName: 'Mahesh Jadhav',
    fromHospitalId: 'hosp-1',
    fromHospitalName: 'PHC Khed',
    toHospitalId: 'hosp-3',
    toHospitalName: 'District Hospital Aundh (Pune)',
    doctorId: 'doc-3',
    doctorName: 'Dr. Vikram Joshi',
    reason: 'Suspected acute coronary syndrome requiring echo & angiogram',
    priority: 'EMERGENCY',
    status: 'CREATED',
    createdAt: '2026-09-06T06:30:00Z',
    currentStage: 'Created',
  },
];

export const INITIAL_BEDS: BedCategory[] = [
  { category: 'ICU', available: 4, occupied: 12, reserved: 2, maintenance: 0, total: 18 },
  { category: 'General', available: 42, occupied: 110, reserved: 8, maintenance: 5, total: 165 },
  { category: 'Emergency', available: 8, occupied: 14, reserved: 3, maintenance: 0, total: 25 },
  { category: 'Pediatric', available: 12, occupied: 28, reserved: 2, maintenance: 1, total: 43 },
  { category: 'Maternity', available: 8, occupied: 38, reserved: 3, maintenance: 0, total: 49 },
];

export const INITIAL_FOLLOW_UPS: FollowUp[] = [
  {
    id: 'fol-1',
    patientId: 'pat-1',
    patientName: 'Ravi Patil',
    doctorId: 'doc-1',
    doctorName: 'Dr. Anand Deshmukh',
    hospitalId: 'hosp-1',
    hospitalName: 'PHC Khed',
    followUpDate: '2026-09-08',
    reason: 'Blood pressure & respiratory progress re-evaluation',
    status: 'PENDING',
    riskLevel: 'MEDIUM',
  },
  {
    id: 'fol-2',
    patientId: 'pat-3',
    patientName: 'Asha Shinde',
    doctorId: 'doc-1',
    doctorName: 'Dr. Anand Deshmukh',
    hospitalId: 'hosp-1',
    hospitalName: 'PHC Khed',
    followUpDate: '2026-09-05',
    reason: 'Diabetes HbA1c review & foot checkup',
    status: 'PENDING',
    riskLevel: 'LOW',
    notes: 'OVERDUE by 1 day',
  },
];

export const INITIAL_HEALTH_ASSESSMENTS: HealthAssessment[] = [
  {
    id: 'ha-1',
    patientId: 'pat-1',
    patientName: 'Ravi Patil',
    workerId: 'wrk-1',
    workerName: 'ASHA Sangeeta Gaikwad',
    symptoms: ['Fever', 'Cough', 'Fatigue'],
    vitals: { bloodPressure: '142/90', heartRate: 88, temperature: 100.4, spo2: 97 },
    assessmentDate: '2026-09-05T09:00:00Z',
    riskLevel: 'MEDIUM',
    notes: 'Patient advised to visit PHC Khed for physician consultation.',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'usr-pat-1',
    type: 'APPOINTMENT',
    title: 'Appointment Confirmed',
    message: 'Your appointment with Dr. Anand Deshmukh at PHC Khed is confirmed for today at 10:00 AM (Token #4).',
    isRead: false,
    createdAt: '2026-09-06T07:00:00Z',
  },
  {
    id: 'notif-2',
    userId: 'usr-pat-1',
    type: 'LAB_REPORT',
    title: 'Lab Report Ready',
    message: 'Your CBC & Fasting Sugar report has been analyzed by PHC Pathology Lab.',
    isRead: true,
    createdAt: '2026-09-01T15:30:00Z',
  },
  {
    id: 'notif-3',
    userId: 'usr-doc-1',
    type: 'EMERGENCY',
    title: 'Emergency Patient In Queue',
    message: 'Mahesh Jadhav (Token #1) flagged as EMERGENCY risk level assigned to Cardiology / Emergency.',
    isRead: false,
    createdAt: '2026-09-06T06:05:00Z',
  },
];
